### ISSUE TITLE
Why is the option :align: from image directive not supported ?

### ISSUE THREAD

**Issue by nicolasmartin3d** [spinus/sphinxcontrib-images#11]
Hello !
Is there a reason for this ? Or did you just forget to support it ? :)

Thanks

**Comment by spinus** [comment]
I didn't forgot, I've never need it.

If you need this do you have few minutes to add this feature?

**Comment by nicolasmartin3d** [comment]
Sure, I submitted a PR for this, let me know !

**Comment by spinus** [comment]
That's very nice, thank you. I asked two questions in PR, please answer. The whole thing looks pretty neat.

**Comment by spinus** [comment]
Hey @nicolasmartin3d , I merge your PR but there were some issues, you set "align left" by default and it was breaking default page layout. I change default align to nothing, the rest was ok. I've added some docs and examples. Please check and if it's good I'll release.

**Comment by nicolasmartin3d** [comment]
It works for me !
Sorry about the default left alignment, it makes more sense to have none.
Thanks

**Comment by spinus** [comment]
@nicolasmartin3d  0.5.0 released https://pypi.python.org/pypi/sphinxcontrib-images/0.5.0, thank you for help.
