### ISSUE TITLE
Search does not work when using the extension

### ISSUE THREAD

**Issue by nicolasmartin3d** [spinus/sphinxcontrib-images#13]
Hey,

This is an issue that was already mentioned here : https://github.com/sphinx-doc/sphinx/issues/1676

This is related to the fact that Lightbox2 is using its own version of jQuery. I'm not sure if this is really needed. After including jquery-1.11.0.min.js, sphinx search script is unhappy with the content of $. 

Anyway, I'm no JS expert, but I fixed it by calling jQuery.noConflict(true) after including everything related to lightbox.

I think this should be looked into if you have some time ... I replied on the other PR by the way :)

Thanks

**Comment by spinus** [comment]
@nicolasmartin3d cheers. I'll add this. 
I know you replied, give me a couple of days, I will test this PR, add jquery no conflict and release new version.

**Comment by spinus** [comment]
@nicolasmartin3d Do you have time to look at branch https://github.com/spinus/sphinxcontrib-images/tree/lightbox-jquery-noconflict? I added what you suggested and it seems work for me, if you could confirm I'll merge it.

**Comment by nicolasmartin3d** [comment]
Yes, it definitely fixes the issue, you should merge it.
Thanks again :+1:

**Comment by spinus** [comment]
nice, thanks for report and for solution.

**Comment by spinus** [comment]
0.5.0 release on PyPI. https://pypi.python.org/pypi/sphinxcontrib-images/0.5.0
