### ISSUE TITLE
Modify dimensions of enlarged images

### ISSUE THREAD

**Issue by vterron** [spinus/sphinxcontrib-images#18]
Is there a way to set the height and width of the images when the user clicks on a thumbnail? I am working with SVG files, so ideally I would like the zoomed images to always be, for example, 75% of the screen size.

**Comment by spinus** [comment]
mhm, currently there it is not possible. After a click, the control is passed to JS "backend" which currently is lightbox2. So, what you can do is to write your backend/extend exisiting one and configure lightbox2 by hand (probably you need something like 2 lines of javascript).

**Comment by vterron** [comment]
Thanks for your prompt response — and the helpful suggestion!
