### ISSUE TITLE
Compatibility with latex builder

### ISSUE THREAD

**Issue by nmartin-cal** [spinus/sphinxcontrib-images#19]
Hey there !
While I understand why there might be no support for latex builder given that this extension if mostly useful in a web environment, I think it might be a good idea to enable the documentation to build in a tex environment anyway. What do you think ?

I guess it would not be too difficult, visitor functions would be added in the Lightbox2 engine to forward the call to the (latex) writer for a 'image_node' (which should work fine since it really is just an image).

Let me know if you think this is a good idea.

**Comment by spinus** [comment]
@nmartin-cal I think you're right and it's good solution. Do you need this feature and have some spare time to implement that?

**Comment by nicolasmartin3d** [comment]
Yeah I'll try to implement this in the next few days.

**Comment by spinus** [comment]
Cheers!

**Comment by nicolasmartin3d** [comment]
Hey ! Sorry about the delay, I thought I had time to work on this before vacations :)
I pushed a PR, let me know.

**Comment by spinus** [comment]
@nicolasmartin3d I merged your PR and moved the code to backend class and updated the docs a little. If you find few minutes please test/check current master and I'll do a release.

**Comment by nicolasmartin3d** [comment]
@spinus Looks great to me ! I can build my documentation with html and latex on my side. Thanks !

**Comment by spinus** [comment]
OK, nice. 0.6.0 released.
