### ISSUE TITLE
problem with thumbnail

### ISSUE THREAD

**Issue by gigster99** [spinus/sphinxcontrib-images#21]
We have these [thumbnails](http://nutrition-database-modernization.readthedocs.org/en/latest/01/new_level_1a.html). What can we do so that they are correctly scaled? The rendered images are presented correctly.

We have experience [using lightbox](http://www.ontomatica.com/public/organizations/ONTO/Concept.html). Is there some combination of lightbox + sphinxcontrib-images that will properly scale the thumbnails?

Thanks in advance for help here.

**Comment by spinus** [comment]
@gigster99 nice one. Thanks for noticing.
So it can be done in two ways.

1. if you know how to do this scaling in CSS properly, probably, it's the way to go.
2. this can be done also on sphinx part. When the thumbnails are collected they might be scaled properly (and sphinxcontrib-images is responsible for it).

Please let me know if you know how to do it in CSS.

**Comment by gigster99** [comment]
Would you show me the CSS solution for sphinx (#1 above). I ask because I'm uncertain about how to properly declare the CSS in the _static directory (which, I believe, is where the updated CSS is installed).

I'm not clear about #2 above. Are you saying that we need to provide a properly scaled thumbnail? I understand that - we had to do the same with the lightbox example above. But with lightbox we had the abilalty to declare the thumbnail *and* the displayed image. I don't see that option with sphinxcontrib-images.

**Comment by spinus** [comment]
1. https://github.com/spinus/sphinxcontrib-images/blob/master/sphinxcontrib_images_lightbox2/lightbox2.py#L10 - this is how additional CSS is included into current LightBox implementation. You could add another file with custom CSS. Btw, if you have any general solution how to resolve this scaling in CSS, I would be happy to implement this.

2. Not really. It's not about providing two images. I think sphinxcontrib-images during image collection phase could create those thumbnails automatically, just I had no time to write that code yet :-)

**Comment by gigster99** [comment]
IMHO, the best approach is two files - a thumbnail and the presented image. Here is the reasoning. If you look at our Lightbox examples above, you will see that the thumbnails are not scaled versions of the presented image; they are 'readable' sections of the presented image. In other words, the thumbnail is a specific image and specific size and is then 'associated' with the presented image.

Also, Lightbox enables a caption. This is not essential but is a useful feature. We render the the caption as title='  ' (for mouseover) and as a legend at the bottom of the presented image.

For your future consideration.

We'll work on your proposal (1 above) and close this issue if we get it working.

TY for your quick response on this.

**Comment by spinus** [comment]
@gigster99 ok, I see your point now.
So if I understand correctly, there are two issues:
1. Thumbnail is not scaled properly.
2. It should be possible to set different image for thumbnail than for target image.
If this is correct, please open two tickets (this one I think is very general :)
And I'll try to work on that.

Cheers for contribution :-)
