### ISSUE TITLE
two images: a thumbnail and presented image

### ISSUE THREAD

**Issue by gigster99** [spinus/sphinxcontrib-images#22]
Please consider support for two image files. One is the presented image. The second is an edited thumbnail image. In both cases, authors will format the images to their specification. The reasoning is this. If a thumbnail is a compressed version of the presented image, it usually is 'unreadable.' If sphinxcontrib-images allowed a specific image to be the thumbnail, the author could edit and scale the presented image into a form that is 'readable' as a thumbnail.

The sphinxcontrib-images default might be the current code. An option would use the edited thumbnail file in place of the generated thumbnail image.

**Comment by spinus** [comment]
@gigster99 Cheers, I'll work on this when I have some spare time.

btw. How you think it should work for other backends, like LaTeX or epub? Should two images be displayed or just the target image?

**Comment by gigster99** [comment]
I don't have an informed opinion because we do not use either one. At the moment our content is hosted on RTD. IMHO the RTD-generated PDF version is of little value (specifically WRT our content - others may know better how to configure their .rst files to be rendered better as PDF files). LaTeX is even trickier. We use LaTeX-related services to render (in HTML) stuff that is [very difficult to do in HTML](http://nutrients.readthedocs.org/en/latest/03_dir/$_03-detail-7-mathematics-1-intro.html#table-of-contents). But we don't need to render our content in (LaTeX) document format.

My uninformed opinion is that the formatted thumbnail file should be the image used in printable output. If author does not use the edited thumbnail (i.e. uses the default rendered thumbnail), then the default thumbnail image would be used.

**Comment by spinus** [comment]
@gigster99 hey, please checkout branch https://github.com/spinus/sphinxcontrib-images/tree/thumbnail. 
You should be able to set up "thumbnail" image for "thumbnail" directive (better name needed :-) I still have some issue with it (with local image, when remote image is used it's ok) so I didn't merge it yet. Please take a look and let me know if you can find any issue. I'll take more probably over next weekend or maybe during a week.

**Comment by gigster99** [comment]
TY; we'll work on this BOD Monday. Will be back 2u with comments.

**Comment by spinus** [comment]
hey, any update? did you have time to test that branch by any chance?

**Comment by gigster99** [comment]
I will do it before the end of the weekend. Your service is part of a product that must be ready at the end of August, so it's a priority. We have a set of dual images (the thumbnail is a non-scaled portion of the main image), and I will use those to test your update. BBTY.

**Comment by spinus** [comment]
@gigster99 thanks for the update. For me there is no rush, I'm only checking :-) Next week I'll have some time so I'll try so go forward with it as well. Cheers.

**Comment by gigster99** [comment]
We've missed our dates again; hence the radio silence. We just implemented a canonical URL on RTD (http://docs.ontomatica.org/en/latest/), which was a priority. Some content management has to be completed next. Then we'll test the images. Thank you for your contribution and patience.

**Comment by spinus** [comment]
@gigster99 no problem, no rush :-) thank you that you want to contribute.
