### ISSUE TITLE
LightBox2 backend needs to un-nativefy image paths

### ISSUE THREAD

**Issue by BugsBunnySan** [spinus/sphinxcontrib-images#27]
Hi!

In sphinxcontrib_images_lightbox2/lightbox2.py, the node['uri'] needs to be converted from whatever os.path.join returns to an html conforming path.

On windows os.path.join returns a path using stupid slashes ('\'), which is not what you want in a URI.

So either don't use os.path (because you don't want a native path here anyway), or replace os.path.sep with '/' afterwards.

kthxbye

**Comment by spinus** [comment]
@BugsBunnySan thanks for reporting. I'll take a look over the weekend.

**Comment by BugsBunnySan** [comment]
@spinus cool, thanks! otherwise it's a really nice extension!

**Comment by BugsBunnySan** [comment]
Oh, also, forgot to add an example...

This directive

`.. thumbnail:: _static/example_stack.png`

got turned into this html:

`<img src="../../../../_images\example_stack1.png"`

**Comment by spinus** [comment]
@BugsBunnySan I've created the fix, but I have no windows at all, could you confirm this is working (please check code from pull request)?

**Comment by spinus** [comment]
should be included in latest release
