### ISSUE TITLE
<script> and <link> tag invalid when compiling under windows

### ISSUE THREAD

**Issue by nikokio** [spinus/sphinxcontrib-images#33]
Hello,

Using lastest Pypi version : 0.7.0

When compiling from Windows, the script and link tags of STATIC_FILES are wrong. Example :

`<script type="text/javascript" src="_static/sphinxcontrib-images/LightBox2\lightbox2\js\jquery-1.11.0.min.js"></script>`

Note the backslashes instead of slashes. The result is lots of 404 errors when the compiled doc is served by a Linux web server.

To quick-fix it, I updated 2 lines in images.install_backend_static_files() adding a replace() : 
`app.add_javascript(os.path.relpath(dest_file_path, STATICS_DIR_PATH).replace('\\', '/'))
app.add_stylesheet(os.path.relpath(dest_file_path, STATICS_DIR_PATH).replace('\\', '/'))`

This is probably not the best way to do...

A fix would be greatly appreciated.

Thanks
Best Regards

**Comment by spinus** [comment]
I'll look at this, thanks for reporting.

**Comment by spinus** [comment]
I'm not maintaining this repo anymore. People from sphinx-contrib are taking care of it now as repo was moved to https://github.com/sphinx-contrib/images.
I'm closing this ticket, if you feel that this issue still exist, please report in its new home on https://github.com/sphinx-contrib/images.
