### ISSUE TITLE
parallel reading not possible

### ISSUE THREAD

**Issue by simone** [spinus/sphinxcontrib-images#35]
WARNING: the sphinxcontrib.images extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read

**Comment by simone** [comment]
probably this can help
http://sphinx.readthedocs.io/en/latest/extdev/appapi.html?highlight=env-merge-info#event-env-merge-info

**Comment by spinus** [comment]
@simone sorry for long delay, thanks for link

**Comment by t-b** [comment]
This was closed in #36 I guess.

**Comment by spinus** [comment]
Thank you @t-b
