### ISSUE TITLE
Disable lightbox if the image is scaled up. 

### ISSUE THREAD

**Issue by daftscience** [spinus/sphinxcontrib-images#37]
I'm trying to figure out the best way to do this, and I understand it might not be easy. 

When the "Thumbnail" is displayed without the ``:width:`` option it will stretch to fill the width of the page. This is really nice, however, when lightbox opens the "preview" ends up being smaller than the thumbnail. 

I'm trying to write some Javascript to fix it, but thought I'd reach out to see if there might be a better way. 

Thanks

**Comment by spinus** [comment]
@daftscience still the case?

**Comment by spinus** [comment]
I'm not maintaining this repo anymore. People from sphinx-contrib are taking care of it now as repo was moved to https://github.com/sphinx-contrib/images.
I'm closing this ticket, if you feel that this issue still exist, please report in its new home on https://github.com/sphinx-contrib/images.
