### ISSUE TITLE
Python private members showing up after installation

### ISSUE THREAD

**Issue by skylogic004** [spinus/sphinxcontrib-images#38]
Using lastest Pypi version : 0.7.0; Windows 7; Python 2.7

After following the installation instructions, the output html now shows private functions and attributes of my classes such as `__doc__, __init__`, etc (which is not desired). When I disable the sphinxcontrib-images extension, these disappear again. 

Any idea why sphinxcontrib-images would interfere with this?

My extensions list in conf.py looks like this:
```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.ext.napoleon',
    'sphinx.ext.mathjax', 
    'sphinxcontrib.images',
]
```

**Comment by spinus** [comment]
Would you mind pasting the output?

**Comment by skylogic004** [comment]
Sorry I'm not still working on this. Original post was 2 years ago; I've moved on.

**Comment by spinus** [comment]
Understood.
