### ISSUE TITLE
Travis Build fail

### ISSUE THREAD

**Issue by knil-sama** [spinus/sphinxcontrib-images#40]
When I created a pull request the travis CI build fail

[build logs](https://travis-ci.org/spinus/sphinxcontrib-images/builds/230723730?utm_source=github_status&utm_medium=notification)

Current error
error: Setup script exited with error in requests setup command: Invalid environment marker: sys_platform == "win32" and python_version<"3.3"

error come from this line in setup.py
        'socks:sys_platform == "win32" and python_version<"3.3"': ['win_inet_pton'],

Tried to upgrade pip in travis but didn't solve the issue, I need to investigate more

**Comment by spinus** [comment]
OK, travis should be much better now, although it's still failing due to some travis issues I think (it cannot download some files, looks like internal travis stuff)
