### ISSUE TITLE
Extension error when run with Sphinx 1.6.1

### ISSUE THREAD

**Issue by rbberger** [spinus/sphinxcontrib-images#41]
The latest changes in Sphinx seem to break this extension. Here is the error message:
```
Running Sphinx v1.6.1
.../lib/python3.6/site-packages/sphinxcontrib/images.py:23: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use the standard library version instead.
  from sphinx.util.compat import Directive

Extension error:
Could not import extension sphinxcontrib.images (exception: cannot import name 'make_admonition')
```

**Comment by danwos** [comment]
Here is a solution how the sphinx extension ablog solved this problem:
https://github.com/abakan/ablog/commit/413566341b36d2b855fdebe133e15edcd4542785

**Comment by ntolia** [comment]
Ran into the same problem. Would be great to get a new release if possible.

**Comment by krallin** [comment]
It seems like this can be worked around in the absence of a new release by inserting the following at the top of `conf.py`:

```
from docutils.parsers.rst.directives.admonitions import BaseAdmonition
from sphinx.util import compat
compat.make_admonition = BaseAdmonition
```

**Comment by ntolia** [comment]
@krallin Thanks. That does seem to work.

**Comment by ntolia** [comment]
Just FYI, the above workaround doesn't work anymore with Sphnix 1.7.x as compat has been removed.

**Comment by ntolia** [comment]
I am moving away from using sphinxcontrib-images for other reasons but applying patches from https://github.com/kellpossible/sphinxcontrib-images/ and then something like the below patch should get things working again. Will obviously require a non-standard pip install.

```diff --git a/sphinxcontrib/images.py b/sphinxcontrib/images.py
index 757fbbf..add4b3e 100644
--- a/sphinxcontrib/images.py
+++ b/sphinxcontrib/images.py
@@ -20,7 +20,10 @@ import sphinx
 from sphinx.locale import _
 from sphinx.environment import NoUri
 from sphinx.util.osutil import copyfile
-from sphinx.util.compat import Directive
+try:
+    from sphinx.util.compat import Directive
+except ImportError:
+    from docutils.parsers.rst import Directive
 from sphinx.util.console import brown
 from sphinx.util.osutil import ensuredir
 from sphinx.util import status_iterator
```

Thanks to @kellpossible for getting the initial stuff out of the way.

**Comment by CollabSensei** [comment]
This is not working for me. Running Sphinx 1.71.

My images.py:
import sphinx
from sphinx.locale import _
from sphinx.environment import NoUri
from sphinx.util.osutil import copyfile
try:
   from sphinx.util.compat import Directive
except ImportError:
   from docutils.parsers.rst import Directive
from sphinx.util.console import brown
from sphinx.util.osutil import ensuredir
from sphinx.util import status_iterator
from docutils import nodes, utils
from docutils.parsers.rst import roles
from docutils.parsers.rst import directives

When compiling a page I get:
Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/images.py", line 235, in download_images
    for src in app.builder.status_iterator(env.remote_images,
AttributeError: 'StandaloneHTMLBuilder' object has no attribute 'status_iterator'

**Comment by t-b** [comment]
Even with the fix from https://github.com/spinus/sphinxcontrib-images/issues/41#issuecomment-367436735 I get 

```
  File "c:\users\test\appdata\local\programs\python\python36\lib\site-packages\sphinxcontrib\images.py", line 232, in download_images
    for src in app.builder.status_iterator(env.remote_images,
AttributeError: 'StandaloneHTMLBuilder' object has no attribute 'status_iterator'
```

with sphinx 1.7.2.

**Comment by nofred** [comment]
@t-b did you fixed the problem? 
I have the same one 
Sphinx 1.7.4

**Comment by t-b** [comment]
@nofred Nope, no time to dig further. Sorry.

**Comment by nofred** [comment]
@t-b thank you
