### ISSUE TITLE
Setting parameters in conf.py

### ISSUE THREAD

**Issue by mandel01** [spinus/sphinxcontrib-images#44]
I am trying to use `sphinxcontrib-images` to format images in a markdown file. (If this won't work I can stop trying!!) I was hoping that by setting defaults in the `conf.py` file this may work. Are there examples of the correct syntax in this file?

The following executes without an error:

```
images_config = {'override_image_directive': True,}
```

However, when I try the following line...

```
images_config = {'override_image_directive': True, 'default_image_width'='50%',}
```
I get this error on build:

```
Running Sphinx v1.5.1

Configuration error:
There is a syntax error in your configuration file: bad input (conf.py, line 38)
Did you change the syntax from 2.x to 3.x?
make: *** [html] Error 1
```

**Comment by wfpinedar** [comment]
try this:

    images_config = {'override_image_directive': False, 'default_image_width': '50%' }

without the ending comma

**Comment by spinus** [comment]
hmm, trailing comma shouldn't matter in that case, that could be something else.
@mandel01 if you have repo with example I could run I could help debug.

**Comment by mandel01** [comment]
Thanks for the input @spinus @wfpinedar. I've moved the site docs to `mkdocs` so I will close this issue.
