### ISSUE TITLE
Incompatible with Sphinx 1.7

### ISSUE THREAD

**Issue by raphaelm** [spinus/sphinxcontrib-images#46]
Hi :) Upgrading to Sphinx 1.7 yields the following error:

```
(env) raphael ~/proj/pretix/doc master $ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.0

Extension error:
Could not import extension sphinxcontrib.images (exception: No module named 'sphinx.util.compat')
make: *** [Makefile:53: html] Fehler 2
```

**Comment by saily** [comment]
This was already fixed in [here&(https://github.com/antaflos/sphinxcontrib-images/commit/8ebee676ce4489da7851cc089cc30fad650913ce). 

I've asked for a pull request.

**Comment by luisbarrancos** [comment]
import status_iterator from sphinx.utll and replace a..builder.status_iterator by status_iterator.
See https://github.com/SciTools/iris/pull/2958/files

**Comment by antaflos** [comment]
I will try to create a PR this week but it needs some changes from another fork as well: https://github.com/kellpossible/sphinxcontrib-images/commit/8155a37d58ac219336d13ff1ca90871bdde48dae as far as I remember.

**Comment by saily** [comment]
@antaflos any updates on this?

**Comment by antaflos** [comment]
@saily I have submitted a PR (#49) but a better one (as far as I can see) is already in the works at #48 so mine was closed.

**Comment by spinus** [comment]
@antaflos @saily @raphaelm - released 0.8.0, would be great if you could confirm that's solved

**Comment by clwilliams8** [comment]
Works locally for me on Sphinx 1.8.2 but when I commit changes and the webhook goes through I get this same error. @saily : I can't figure out where the sphinxcontrib/images.py file is to make that fix you are talking about?

**Comment by spinus** [comment]
that sounds like setup issue. Are you running this in virtualenv?

**Comment by spinus** [comment]
I'm not maintaining this repo anymore. People from sphinx-contrib are taking care of it now as repo was moved to https://github.com/sphinx-contrib/images.
I'm closing this ticket, if you feel that this issue still exist, please report in its new home on https://github.com/sphinx-contrib/images.
