### ISSUE TITLE
Building documentation fails 

### ISSUE THREAD

**Issue by nofred** [spinus/sphinxcontrib-images#47]
Hi,

When running with 1.7.4 I get the following error:
`AttributeError: 'StandaloneHTMLBuilder' object has no attribute 'status_iterator'`

**Comment by stefanodavid** [comment]
I confirm the problem, using sphinx 1.7.6 and the patch mentioned in #46:

`Exception occurred:
  File "/usr/local/lib/python2.7/dist-packages/sphinxcontrib/images.py", line 236, in download_images
    for src in app.builder.status_iterator(env.remote_images,
AttributeError: 'StandaloneHTMLBuilder' object has no attribute 'status_iterator'
`

**Comment by luisbarrancos** [comment]
Import status_iterator from sphinx.util replace app.builder.status_iterator by status_iterator, see
https://github.com/SciTools/iris/pull/2958/files

**Comment by spinus** [comment]
@nofred would you mind checking if that's fixed now?

**Comment by nofred** [comment]
@spinus it's working, thank you
