### ISSUE TITLE
Does not seem to work for relative image in ../

### ISSUE THREAD

**Issue by hgrecco** [spinus/sphinxcontrib-images#5]
I have the following image **working** code in my docs:
```
    .. image:: ../_static/some.png
```
but trying to use is a thumbnail:
```
    .. thumbnail:: ../_static/some,png
        :width: 20%
```
does not work.
```
ValueError: Image URI `../_static/some.png` have to be local relative or absolute path to image, or remote address.
```

Just a side note, it works fine for images not referenced as `../` but this force me to put the images in the same folder or subfolders of the rst file.

**Comment by hgrecco** [comment]
Looking at the code, I guess is a problem with `is_remote`. I am submitting a patch but it is not nice as it only take `/` like the current code.

**Comment by spinus** [comment]
@hgrecco thanks for report. Do you think https://github.com/spinus/sphinxcontrib-images/pull/7/files would solve your problem or you need specifically '..'?

**Comment by hgrecco** [comment]
Should work! Are you planning to release it soon?

**Comment by spinus** [comment]
I'll wait for answer from @zatan, in ~2 days is ok?

**Comment by hgrecco** [comment]
sounds good. Thanks.

**Comment by spinus** [comment]
@hgrecco done.
