### ISSUE TITLE
Allow to use thumbnails with graphviz directive

### ISSUE THREAD

**Issue by t-b** [spinus/sphinxcontrib-images#53]
I'm embedding graphviz dot files via

```rst
.. graphviz:: ../multi-patch-seq-fast-rheo-estimate.dot
```

into my documentation.

And as these graphs can get quite large I would like to override the sphinx behaviour here as well. `override_image_directive` does only work with `image` AFAIU.

**Comment by spinus** [comment]
@t-b I won't have time to implement that, but happy to merge patch if you would have one.

**Comment by spinus** [comment]
I'm not maintaining this repo anymore. People from sphinx-contrib are taking care of it now as repo was moved to https://github.com/sphinx-contrib/images.
I'm closing this ticket, if you feel that this issue still exist, please report in its new home on https://github.com/sphinx-contrib/images.
