### ISSUE TITLE
Support Sphinx 2+

### ISSUE THREAD

**Issue by oberstet** [spinus/sphinxcontrib-images#55]
`sphinxcontrib-images` has `sphinx>=1.1.3,<2` as dependency - but as sphinx 2.0.0 has recently been released (03/28), this broke our builds - version conflict, as we install sphinx with open ended version currently.

**Comment by ukos-git** [comment]
I would also love if this PR could be accepted soon as I'm getting the incompatibility warning in [sphinxcontrib-images-0.8.0](https://github.com/spinus/sphinxcontrib-images/tree/0.8.0) using python3.

```
Start sphinx-build
/usr/local/lib/python3.7/dist-packages/sphinxcontrib/images.py:320: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  app.info('Initiated sphinxcontrib-images backend: ', nonl=True)
/usr/local/lib/python3.7/dist-packages/sphinxcontrib/images.py:322: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  ':' + backend.__class__.__name__)))
^C
interrupted!
```

**Comment by spinus** [comment]
I'm not maintaining this repo anymore. People from sphinx-contrib are taking care of it now as repo was moved to https://github.com/sphinx-contrib/images.
I'm closing this ticket, if you feel that this issue still exist, please report in its new home on https://github.com/sphinx-contrib/images.
