### ISSUE TITLE
Deprecation warnings are generated for app.info() calls

### ISSUE THREAD

**Issue by charles-at-undo** [spinus/sphinxcontrib-images#57]
When the backend is initialised, a deprecation warning is generated:

```
Running Sphinx v1.8.1
making output directory...
/var/lib/jenkins/somepath/venv/lib/python2.7/site-packages/sphinx/application.py:402: RemovedInSphinx20Warning: app.info() is now deprecated. Use sphinx.util.logging instead.
  RemovedInSphinx20Warning)
Initiated sphinxcontrib-images backend: `sphinxcontrib_images_lightbox2.lightbox2:LightBox2`
building [mo]: targets for 0 po files that are out of date
```

Apparently this should be upgraded to sphinx.util.logging().

**Comment by spinus** [comment]
I'm not maintaining this repo anymore. People from sphinx-contrib are taking care of it now as repo was moved to https://github.com/sphinx-contrib/images.
I'm closing this ticket, if you feel that this issue still exist, please report in its new home on https://github.com/sphinx-contrib/images.
